# Generated by Django 6.0.3 on 2026-03-07 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
