# Generated by Django 6.0.3 on 2026-03-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='house_num',
            field=models.CharField(help_text='enter your building/house number e.g: F/406', max_length=50),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
