# Generated by Django 6.0.3 on 2026-03-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_useraddress_house_num_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name_plural': 'User Addresses'},
        ),
    ]
