# Generated by Django 6.0.3 on 2026-03-14 05:22

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=products.models.product_image_upload_path),
        ),
    ]
