# Generated by Django 6.0.3 on 2026-03-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_quantity_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
