# Generated by Django 6.0.3 on 2026-03-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_images_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selling',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
